package com.dark.sdk

/**
 * Build configuration constants
 * Generated by Gradle during build
 */
object BuildConfig {
    const val VERSION_NAME = "2.0.0-ELITE"
    const val VERSION_CODE = 200
    const val DEBUG = false
    const val APPLICATION_ID = "com.dark.sdk"
    const val BUILD_TYPE = "release"
    const val FLAVOR = ""
    const val CORE_TYPE = "ELITE"
    const val CORE_VARIANT = "D-Z-B"
    const val ELITE_MIC_FIX = true
    const val ELITE_ANOGS_FIX = true
    const val ELITE_AUTH_FIX = true
}